---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      python-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns: ["*"]
